/**
 * Mock Data for Soirée MVP
 *
 * Provides venue data, detail data (hours, gallery, gender ratios),
 * and loyalty tasks as fallback when Supabase is empty.
 */

import type { Venue, LoyaltyTask } from "./types";

// ── Mock Venues ─────────────────────────────────────────────

export const MOCK_VENUES: Venue[] = [
    {
        id: "v-001",
        name: "Rebel",
        address: "11 Polson St, Toronto",
        latitude: 43.6398,
        longitude: -79.3553,
        venue_type: "nights",
        venue_category: "club",
        music_types: ["EDM", "House"],
        vibes: ["Rave"],
        age_range_min: 19,
        age_range_max: 35,
        dress_code: "Smart casual",
        current_density: 78,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-002",
        name: "Toybox",
        address: "473 Adelaide St W, Toronto",
        latitude: 43.6464,
        longitude: -79.3979,
        venue_type: "nights",
        venue_category: "club",
        music_types: ["Hip-Hop", "R&B"],
        vibes: ["Hip hop", "Rave"],
        age_range_min: 19,
        age_range_max: 30,
        dress_code: "Dress to impress",
        current_density: 85,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-003",
        name: "CODA",
        address: "794 Bathurst St, Toronto",
        latitude: 43.6631,
        longitude: -79.4113,
        venue_type: "nights",
        venue_category: "club",
        music_types: ["Techno", "House"],
        vibes: ["Rave"],
        age_range_min: 19,
        age_range_max: 40,
        dress_code: null,
        current_density: 62,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-004",
        name: "EFS Toronto",
        address: "647 King St W, Toronto",
        latitude: 43.6443,
        longitude: -79.4015,
        venue_type: "tickets",
        venue_category: "club",
        music_types: ["Hip-Hop", "R&B", "Afrobeats"],
        vibes: ["Upscale", "Hip hop"],
        age_range_min: 19,
        age_range_max: 35,
        dress_code: "Upscale dress code",
        current_density: 90,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-005",
        name: "Lavelle",
        address: "627 King St W, Toronto",
        latitude: 43.6446,
        longitude: -79.4007,
        venue_type: "tickets",
        venue_category: "rooftop",
        music_types: ["House", "R&B"],
        vibes: ["Upscale", "Chill"],
        age_range_min: 21,
        age_range_max: 40,
        dress_code: "Upscale",
        current_density: 55,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-006",
        name: "The Drake Hotel",
        address: "1150 Queen St W, Toronto",
        latitude: 43.6432,
        longitude: -79.4252,
        venue_type: "listings",
        venue_category: "lounge",
        music_types: ["House", "Disco"],
        vibes: ["Chill", "Upscale"],
        age_range_min: 19,
        age_range_max: 45,
        dress_code: null,
        current_density: 40,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-007",
        name: "The Horseshoe Tavern",
        address: "370 Queen St W, Toronto",
        latitude: 43.6494,
        longitude: -79.3949,
        venue_type: "listings",
        venue_category: "bar",
        music_types: ["Pop", "Jazz"],
        vibes: ["Chill"],
        age_range_min: 19,
        age_range_max: 50,
        dress_code: null,
        current_density: 32,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-008",
        name: "The Mahjong Bar",
        address: "136 Ossington Ave, Toronto",
        latitude: 43.6463,
        longitude: -79.4222,
        venue_type: "nights",
        venue_category: "lounge",
        music_types: ["R&B", "Hip-Hop"],
        vibes: ["Upscale", "Chill"],
        age_range_min: 19,
        age_range_max: 35,
        dress_code: "Smart casual",
        current_density: 70,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-009",
        name: "Handlebar",
        address: "159 Augusta Ave, Toronto",
        latitude: 43.6533,
        longitude: -79.4015,
        venue_type: "listings",
        venue_category: "bar",
        music_types: ["Latin", "Afrobeats"],
        vibes: ["Chill", "Hip hop"],
        age_range_min: 19,
        age_range_max: 40,
        dress_code: null,
        current_density: 48,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-010",
        name: "Cube Nightclub",
        address: "314 Queen St W, Toronto",
        latitude: 43.6498,
        longitude: -79.3932,
        venue_type: "tickets",
        venue_category: "club",
        music_types: ["EDM", "Techno", "House"],
        vibes: ["Rave"],
        age_range_min: 19,
        age_range_max: 30,
        dress_code: "No dress code",
        current_density: 72,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-011",
        name: "Lost & Found",
        address: "577 King St W, Toronto",
        latitude: 43.6448,
        longitude: -79.3985,
        venue_type: "nights",
        venue_category: "club",
        music_types: ["Hip-Hop", "Afrobeats", "R&B"],
        vibes: ["Hip hop", "Rave"],
        age_range_min: 19,
        age_range_max: 30,
        dress_code: "Dress to impress",
        current_density: 88,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-012",
        name: "Apt 200",
        address: "204 Adelaide St W, Toronto",
        latitude: 43.6486,
        longitude: -79.3880,
        venue_type: "listings",
        venue_category: "bar",
        music_types: ["R&B", "Hip-Hop"],
        vibes: ["Chill", "Hip hop"],
        age_range_min: 19,
        age_range_max: 30,
        dress_code: null,
        current_density: 58,
        created_at: new Date().toISOString(),
    },
    {
        id: "v-013",
        name: "Nest",
        address: "423 College St, Toronto",
        latitude: 43.6562,
        longitude: -79.4058,
        venue_type: "tickets",
        venue_category: "club",
        music_types: ["Afrobeats", "Latin", "Hip-Hop"],
        vibes: ["Hip hop", "Rave"],
        age_range_min: 19,
        age_range_max: 28,
        dress_code: "Smart casual",
        current_density: 65,
        created_at: new Date().toISOString(),
    },
];

// ── Mock Hours ──────────────────────────────────────────────

export const MOCK_HOURS: Record<string, Record<string, string>> = {
    "v-001": { friday: "10PM–3AM", saturday: "10PM–3AM", thursday: "10PM–2AM", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-002": { friday: "10PM–2:30AM", saturday: "10PM–2:30AM", thursday: "9PM–2AM", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-003": { friday: "11PM–4AM", saturday: "11PM–4AM", thursday: "11PM–3AM", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-004": { friday: "10PM–2AM", saturday: "10PM–2AM", thursday: "Closed", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-005": { friday: "5PM–2AM", saturday: "5PM–2AM", thursday: "5PM–12AM", wednesday: "5PM–12AM", tuesday: "Closed", monday: "Closed", sunday: "12PM–10PM" },
    "v-006": { friday: "5PM–2AM", saturday: "5PM–2AM", thursday: "5PM–1AM", wednesday: "5PM–12AM", tuesday: "5PM–12AM", monday: "5PM–12AM", sunday: "11AM–12AM" },
    "v-007": { friday: "8PM–2AM", saturday: "8PM–2AM", thursday: "8PM–1AM", wednesday: "8PM–1AM", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-008": { friday: "6PM–2AM", saturday: "6PM–2AM", thursday: "6PM–1AM", wednesday: "6PM–12AM", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-011": { friday: "10PM–2:30AM", saturday: "10PM–2:30AM", thursday: "10PM–2AM", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
    "v-013": { friday: "10PM–3AM", saturday: "10PM–3AM", thursday: "Closed", wednesday: "Closed", tuesday: "Closed", monday: "Closed", sunday: "Closed" },
};

// ── Mock Gallery (colored placeholders for MVP) ─────────────

export const MOCK_GALLERY: Record<string, string[]> = {
    "v-001": [
        "linear-gradient(135deg, #6d28d9, #ec4899)",
        "linear-gradient(135deg, #1e1b4b, #312e81)",
        "linear-gradient(135deg, #581c87, #7e22ce)",
        "linear-gradient(135deg, #0f172a, #1e293b)",
    ],
    "v-002": [
        "linear-gradient(135deg, #7c3aed, #f43f5e)",
        "linear-gradient(135deg, #1e1b4b, #4338ca)",
        "linear-gradient(135deg, #312e81, #6d28d9)",
    ],
    "v-004": [
        "linear-gradient(135deg, #f59e0b, #d97706)",
        "linear-gradient(135deg, #78350f, #92400e)",
        "linear-gradient(135deg, #451a03, #78350f)",
        "linear-gradient(135deg, #7c2d12, #c2410c)",
    ],
    "v-005": [
        "linear-gradient(135deg, #f59e0b, #fbbf24)",
        "linear-gradient(135deg, #92400e, #b45309)",
        "linear-gradient(135deg, #78350f, #a16207)",
    ],
    "v-008": [
        "linear-gradient(135deg, #8b5cf6, #a78bfa)",
        "linear-gradient(135deg, #1e1b4b, #3730a3)",
        "linear-gradient(135deg, #4c1d95, #6d28d9)",
    ],
    "v-011": [
        "linear-gradient(135deg, #7c3aed, #ec4899)",
        "linear-gradient(135deg, #312e81, #6366f1)",
        "linear-gradient(135deg, #1e1b4b, #4338ca)",
        "linear-gradient(135deg, #581c87, #a855f7)",
    ],
};

// ── Mock Gender Ratios ──────────────────────────────────────

export const MOCK_GENDER_RATIOS: Record<string, { male: number; female: number }> = {
    "v-001": { male: 60, female: 40 },
    "v-002": { male: 55, female: 45 },
    "v-003": { male: 65, female: 35 },
    "v-004": { male: 50, female: 50 },
    "v-005": { male: 45, female: 55 },
    "v-006": { male: 55, female: 45 },
    "v-007": { male: 60, female: 40 },
    "v-008": { male: 48, female: 52 },
    "v-009": { male: 55, female: 45 },
    "v-010": { male: 58, female: 42 },
    "v-011": { male: 52, female: 48 },
    "v-012": { male: 55, female: 45 },
    "v-013": { male: 50, female: 50 },
};

// ── Mock Loyalty Tasks (Soirée partner venues only) ─────────

export const MOCK_LOYALTY_TASKS: LoyaltyTask[] = [
    // Rebel
    { id: "lt-001", venue_id: "v-001", task_description: "Check in before 11 PM", reward_description: "50% off first 2 shots", xp_value: 25, active: true, created_at: new Date().toISOString() },
    { id: "lt-002", venue_id: "v-001", task_description: "Visit 3 times this month", reward_description: "Free cover charge", xp_value: 50, active: true, created_at: new Date().toISOString() },
    // Toybox
    { id: "lt-003", venue_id: "v-002", task_description: "Arrive before midnight", reward_description: "Complimentary drink", xp_value: 30, active: true, created_at: new Date().toISOString() },
    { id: "lt-004", venue_id: "v-002", task_description: "Bring 3+ friends", reward_description: "VIP table upgrade", xp_value: 75, active: true, created_at: new Date().toISOString() },
    // CODA
    { id: "lt-005", venue_id: "v-003", task_description: "Check in on a Thursday", reward_description: "2-for-1 drinks", xp_value: 20, active: true, created_at: new Date().toISOString() },
    // EFS
    { id: "lt-006", venue_id: "v-004", task_description: "Reserve VIP before 9 PM", reward_description: "Bottle service discount 20%", xp_value: 40, active: true, created_at: new Date().toISOString() },
    { id: "lt-007", venue_id: "v-004", task_description: "Tag @EFS on Instagram story", reward_description: "Free appetizer platter", xp_value: 15, active: true, created_at: new Date().toISOString() },
    // Lavelle
    { id: "lt-008", venue_id: "v-005", task_description: "Visit on a Sunday", reward_description: "Rooftop access + welcome drink", xp_value: 35, active: true, created_at: new Date().toISOString() },
    // Mahjong Bar
    { id: "lt-009", venue_id: "v-008", task_description: "Check in 5 times total", reward_description: "Signature cocktail on the house", xp_value: 60, active: true, created_at: new Date().toISOString() },
    // Lost & Found
    { id: "lt-010", venue_id: "v-011", task_description: "Check in before 11 PM", reward_description: "Skip the line pass", xp_value: 30, active: true, created_at: new Date().toISOString() },
    { id: "lt-011", venue_id: "v-011", task_description: "Visit on consecutive weekends", reward_description: "Free cover + drink ticket", xp_value: 55, active: true, created_at: new Date().toISOString() },
    // Cube
    { id: "lt-012", venue_id: "v-010", task_description: "Check in on event night", reward_description: "Discounted entry 50% off", xp_value: 25, active: true, created_at: new Date().toISOString() },
    // Nest
    { id: "lt-013", venue_id: "v-013", task_description: "Share event on Soirée", reward_description: "Free cover charge", xp_value: 20, active: true, created_at: new Date().toISOString() },
];
